### ISSUE TITLE
no-check to use LOM objects before initialized

### ISSUE THREAD

**Issue by h1data** [h1data/M4L-ioRouting-js#2]
It would misfire before the init function in certain situations.
i.e. using amxd outside of Ableton.

**Comment by AffeZwei** [comment]
!isInitialized is added to other functions already, so adding it to settype and setchannel can help fix this.

**Comment by h1data** [comment]
Thanks, Ma'am. I have read the discussion on Discord.
I'd like to reproduce it by myself and understand the behavior and why the function was called before `init`.
One possibility is to set "Parameter Visibility" to other than "hidden" for `live.menu` to store selected values.

Just made an issue for my reminder and I'm postponing this...

**Comment by AffeZwei** [comment]
Thanks, this makes sense as well.
Best wishes,
AZ

**Comment by h1data** [comment]
I understand. I will also fix README.md to add a description that
`live.menu` should not store selected values but M4L remembers routing info within itself.
